[package]
name = "r2-sav-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.72", features = ["backtrace"] }
byteorder = "1.4.3"
crc32fast = "1.3.2"
flate2 = { version = "1.0.26" }
serde = { version = "1.0.182", features = ["derive"] }
serde_json = "1.0.104"
